In [4]:
import torch
from torch import nn
import numpy as np

a=torch.from_numpy(np.array([[1,2],[3,4],[6,9]]))
print(a.max(0))
print(a.max(0)[0])
print(a.max(1))
print(a.max(1)[0])

torch.return_types.max(
values=tensor([6, 9]),
indices=tensor([2, 2]))
tensor([6, 9])


In [6]:
b=torch.tensor([1,2,3,4,5])
# 解缩，加一个维度，就是加中括号，dim=0是加在最外层，dim=1是次外层，以此类推
print(torch.unsqueeze(b,0))
print(torch.unsqueeze(b,1))
print(torch.unsqueeze(b,-1))
print(torch.unsqueeze(b,-2))

tensor([[1, 2, 3, 4, 5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[1, 2, 3, 4, 5]])


In [7]:
c=torch.tensor([[1,2],[3,4]])
print(torch.unsqueeze(c,0))
print(torch.unsqueeze(c,1))
print(torch.unsqueeze(c,2))
print(torch.unsqueeze(c,-1)) 
print(torch.unsqueeze(c,-2))
print(torch.unsqueeze(c,-3))

tensor([[[1, 2],
         [3, 4]]])
tensor([[[1, 2]],

        [[3, 4]]])
tensor([[[1],
         [2]],

        [[3],
         [4]]])
tensor([[[1],
         [2]],

        [[3],
         [4]]])
tensor([[[1, 2]],

        [[3, 4]]])
tensor([[[1, 2],
         [3, 4]]])
