In [20]:
import os

path="../mnist/"

print(os.listdir('../mnist/'))

print(len([f for f in os.listdir(path) if not f.startswith('.')])>0)

['MNIST', '.DS_Store']
True


In [31]:
import torch
a=torch.tensor([1,2,3,4])
b=torch.ones(2,2)
c=torch.zeros(3,3)
print(a,'\n',b,'\n',c)
print(a.size(),b.size(),c.size())
t=torch.empty(3,4,5)
print(t)
print(t.type())


tensor([1, 2, 3, 4]) 
 tensor([[1., 1.],
        [1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([4]) torch.Size([2, 2]) torch.Size([3, 3])
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
torch.FloatTensor


In [14]:
import os
print(os.getcwd()+'/..')
print(type(os.getcwd()))

/Users/yuxiang/Documents/3MyProjects/summer@thu-sz/machine-learning-algorithms/CNN/..
<class 'str'>
